enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
patches-version = "v4.12.0-dev.9"
integrations-version = "v1.12.0-dev.6"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
excluded-patches = "'Custom branding'"
included-patches = "'Remove player controls background'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music]
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "both"
excluded-patches = "'Custom branding'"

[Twitter]
build-mode = "apk"
version = "10.49.0-release.0"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"

[Instagram]
build-mode = "apk"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
